import type { GrowResponse } from "./grow.js";

export const mockGrowResponse: GrowResponse = {
  currency: "PKR",
  summary: {
    title: "Your money garden is calm today",
    subtitle:
      "Goals are growing steadily. NAVs are here for context, not pressure.",
    totalGardenValue: 837500,
    todayChange: 3200,
  },
  savingsGoals: [
    {
      id: "car-fund",
      name: "Car fund",
      target: 1200000,
      saved: 420000,
      pct: 0.35,
      currency: "PKR",
      category: "car",
      monthlyPlant: 45000,
      nextMilestonePct: 0.5,
      milestoneLabel: "Halfway shade",
      recommendedAction: {
        title: "Plant PKR 10,000 this week",
        xp: 25,
        impact: "+15% of the next milestone",
      },
    },
    {
      id: "eidi-envelope",
      name: "Eidi envelope",
      target: 80000,
      saved: 64000,
      pct: 0.8,
      currency: "PKR",
      category: "eidi",
      monthlyPlant: 12000,
      nextMilestonePct: 1,
      milestoneLabel: "Ready for Eid",
      recommendedAction: {
        title: "Add PKR 6,000 before month end",
        xp: 20,
        impact: "Goal can finish one month early",
      },
    },
    {
      id: "zakat-plan",
      name: "Zakat plan",
      target: 180000,
      saved: 90000,
      pct: 0.5,
      currency: "PKR",
      category: "zakat",
      monthlyPlant: 15000,
      nextMilestonePct: 0.75,
      milestoneLabel: "Three-quarter bloom",
      recommendedAction: {
        title: "Set aside PKR 15,000 after salary",
        xp: 20,
        impact: "+25% progress toward the next bloom",
      },
    },
  ],
  emergencyFund: {
    saved: 348000,
    target: 600000,
    pct: 0.58,
    monthsCovered: 3.2,
    targetMonths: 6,
    status: "steady",
    encouragement:
      "A 3.2 month buffer is a steady cushion. Keep building before taking extra risk.",
    recommendedAction: {
      title: "Move PKR 20,000 to emergency savings",
      xp: 25,
      impact: "+0.2 months of cover",
    },
  },
  investments: {
    totalValue: 325000,
    dayChange: 3200,
    dayChangePct: 0.99,
    currency: "PKR",
    mutualFunds: [
      {
        id: "al-meezan-cash",
        fundName: "Al Meezan Cash Fund",
        provider: "Al Meezan",
        category: "Money Market",
        nav: 54.2187,
        units: 2800,
        marketValue: 151812,
        returnPct: 0.42,
        navDate: "2026-07-04",
        tone: "calm",
      },
      {
        id: "meezan-sovereign",
        fundName: "Meezan Sovereign Fund",
        provider: "Al Meezan",
        category: "Income",
        nav: 63.4471,
        units: 1900,
        marketValue: 120549,
        returnPct: 1.1,
        navDate: "2026-07-04",
        tone: "growing",
      },
      {
        id: "al-meezan-equity",
        fundName: "Al Meezan Mutual Fund",
        provider: "Al Meezan",
        category: "Equity",
        nav: 17.5462,
        units: 3000,
        marketValue: 52639,
        returnPct: -0.35,
        navDate: "2026-07-04",
        tone: "watch",
      },
    ],
    cashGoals: [
      {
        label: "Meezan savings",
        amount: 348000,
        currency: "PKR",
      },
      {
        label: "Wise rainy-day cash",
        amount: 164500,
        currency: "PKR",
      },
    ],
    note: "NAVs are read-only mock data from a MUFAP-style snapshot. Sprout will never rush you to invest.",
  },
  milestones: [
    {
      thresholdPct: 0.25,
      title: "First leaves",
      xp: 15,
      celebrated: true,
    },
    {
      thresholdPct: 0.5,
      title: "Strong stem",
      xp: 25,
      celebrated: false,
    },
    {
      thresholdPct: 0.75,
      title: "Fresh shade",
      xp: 35,
      celebrated: false,
    },
    {
      thresholdPct: 1,
      title: "Fully funded",
      xp: 50,
      celebrated: false,
    },
  ],
  emptyState: {
    title: "Plant your first money goal",
    subtitle:
      "Start with any amount. Sprout can track it manually even with zero bank connections.",
    actionLabel: "Create a goal",
  },
};
