import type { BudgetResponse } from "./budget.js";

export const mockBudgetResponse: BudgetResponse = {
  currency: "PKR",
  period: {
    monthLabel: "July 2026",
    startsOn: "2026-07-01",
    endsOn: "2026-07-31",
    daysElapsed: 5,
    daysTotal: 31,
  },
  categories: [
    {
      id: "chai",
      category: "Chai and snacks",
      budgeted: 9000,
      spent: 4200,
      band: "healthy",
      typicalForYou: 8200,
      factor: "Tiny daily spends are still inside your usual rhythm.",
    },
    {
      id: "groceries",
      category: "Groceries",
      budgeted: 45000,
      spent: 38900,
      band: "watch",
      typicalForYou: 42000,
      factor:
        "Groceries are close to the monthly plan after the first big run.",
    },
    {
      id: "fuel",
      category: "Fuel",
      budgeted: 28000,
      spent: 31200,
      band: "over",
      typicalForYou: 26000,
      factor: "Fuel is ahead of plan; one no-drive errand day can soften it.",
    },
    {
      id: "ride-hailing",
      category: "Ride-hailing",
      budgeted: 12000,
      spent: 6100,
      band: "healthy",
      typicalForYou: 13500,
      factor: "Careem and rickshaw spend is lighter than your usual month.",
    },
    {
      id: "mobile-load",
      category: "Mobile load",
      budgeted: 5500,
      spent: 5200,
      band: "watch",
      typicalForYou: 5000,
      factor: "Most of the mobile bundle is already used for the month.",
    },
    {
      id: "utilities",
      category: "Utilities",
      budgeted: 22000,
      spent: 9500,
      band: "healthy",
      typicalForYou: 21000,
      factor: "K-Electric and gas payments are tracking normally.",
    },
    {
      id: "school-fee",
      category: "School fee",
      budgeted: 30000,
      spent: 30000,
      band: "healthy",
      typicalForYou: 30000,
      factor: "School fee is paid and no extra amount is expected.",
    },
    {
      id: "committee-bc",
      category: "Committee / BC",
      budgeted: 25000,
      spent: 25000,
      band: "healthy",
      typicalForYou: 25000,
      factor: "Committee contribution is complete for July.",
    },
    {
      id: "zakat",
      category: "Zakat",
      budgeted: 15000,
      spent: 10000,
      band: "healthy",
      typicalForYou: 12000,
      factor: "Giving is planned and still has room.",
    },
    {
      id: "rent",
      category: "Rent",
      budgeted: 85000,
      spent: 85000,
      band: "healthy",
      typicalForYou: 85000,
      factor: "Rent is covered for the month.",
    },
  ],
  upcomingBills: [
    {
      id: "bill-school-transport",
      name: "School transport",
      amount: 8500,
      currency: "PKR",
      dueDate: "2026-07-07",
      dueRisk: "high",
      note: "Due soon and not marked as paid yet.",
    },
    {
      id: "bill-internet",
      name: "StormFiber internet",
      amount: 4200,
      currency: "PKR",
      dueDate: "2026-07-10",
      dueRisk: "medium",
      note: "Covered if this week's eating-out pace stays steady.",
    },
    {
      id: "bill-committee",
      name: "Committee top-up",
      amount: 12000,
      currency: "PKR",
      dueDate: "2026-07-15",
      dueRisk: "low",
      note: "Enough time to set aside gradually.",
    },
  ],
  totals: {
    budgeted: 276500,
    spent: 245100,
    remaining: 31400,
    paceRatio: 1.08,
    billsAtRiskTotal: 8500,
  },
  recommendedAction: {
    title: "Keep fuel under PKR 4,000 this week",
    xp: 15,
    impact: "+2 health score",
  },
};
